language: php

sudo: false

matrix:
    include:
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 5.3
        - php: 5.6
        - php: 7.0
        - php: nightly
        - php: hhvm
    allow_failures:
        - php: nightly
        - php: hhvm
    fast_finish: true

before_install:
    - composer self-update

install:
    - composer --prefer-dist -o install

script:
    - phpunit --configuration phpunit.xml.dist

notifications:
    email:
        - will@willwh.com

branches:
    only:
        - master
        - 2.1
